name: Build CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-02-22
        override: true
        components: rustfmt
    - name: Check code format
      run: cd kernel && cargo fmt -- --check

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-02-22
        components: rust-src, clippy, llvm-tools-preview
    - name: Setup environment
      run: make -C kernel env ARCH=${{ matrix.arch }}

    - name: Install musl toolchain
      run: |
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          export MUSL_PATH="aarch64-linux-musl-cross"
        fi
        wget https://musl.cc/$MUSL_PATH.tgz
        tar -xf aarch64-linux-musl-cross.tgz
        mv $MUSL_PATH musl

    - name: Build kernel
      run: |
        export PATH=$PATH:$PWD/musl/bin
        make -C kernel ARCH=${{ matrix.arch }}

    - name: Clippy
      run: make -C kernel clippy ARCH=${{ matrix.arch }}
